name: gatopedia
description: Uma enciclop√©dia de gatos!
publish_to: "none"
version: 2.0.0-part1.build1+15

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.6
  just_audio: ^0.10.0
  path_provider: ^2.1.5
  another_flushbar: ^1.12.30
  package_info_plus: ^9.0.0
  animations: ^2.0.11
  shared_preferences: ^2.2.3
  firebase_core: ^4.1.0
  firebase_database: ^12.0.1
  firebase_storage: ^13.0.1
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.3.0
  flutter_expandable_fab: ^2.0.0
  photo_view: ^0.15.0
  material_symbols_icons: ^4.2741.0
  firebase_app_check: ^0.4.0+1
  connecteo: ^3.0.0
  lottie: ^3.1.1
  grayscale: ^0.0.5+7
  http: ^1.2.1
  flutter_blurhash: ^0.9.1
  google_sign_in: ^7.1.1
  icons_plus: ^5.0.0
  file_picker: ^10.0.0
  image_picker: ^1.1.2
  icons_launcher: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  in_app_update: ^4.2.3
  fluttertoast: ^9.0.0
  translator: ^1.0.3+1
  uuid: ^4.5.2
  transparent_image: ^2.0.1
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/
    - assets/animations/
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost.ttf
    - family: DanIcons
      fonts:
        - asset: assets/fonts/DanIcons.ttf

flutter_native_splash:
  image: assets/splash/icon.png
  color: "#fbf8ff"
  branding: assets/splash/createdby-light.png

  color_dark: "#131318"
  branding_dark: assets/splash/createdby-dark.png

  ios: true
  android: false
  web: true